language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs
  - sudo apt-get install -y scala
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh
  - curl -s get.sdkman.io | bash; source /home/travis/.sdkman/bin/sdkman-init.sh; sdk install kotlin

script:
  - make build
  - bash script/test.sh
