language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh
  - curl -s get.sdkman.io | bash
  - source /home/travis/.sdkman/bin/sdkman-init.sh
  - yes | sdk install groovy
  - yes | sdk install kotlin
  - yes | sdk install scala

script:
  - make build
  - bash script/test.sh
