language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y gnustep-devel
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs mono-complete mono-vbnc fsharp
  - wget http://www.scala-lang.org/files/archive/scala-2.12.6.deb; sudo dpkg -i scala-2.12.6.deb
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh
  - wget https://swift.org/builds/swift-4.1.3-release/ubuntu1604/swift-4.1.3-RELEASE/swift-4.1.3-RELEASE-ubuntu16.04.tar.gz && tar xzvf swift-4.1.3-RELEASE-ubuntu16.04.tar.gz && export PATH=$PWD/swift-4.1.3-RELEASE-ubuntu16.04/usr/bin:$PATH
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.2.60/kotlin-compiler-1.2.60.zip; unzip kotlin-compiler-1.2.60.zip; export PATH=$PWD/kotlinc/bin:$PATH
  - sudo apt-get install -y groovy
  - wget http://downloads.dlang.org/releases/2016/dmd_2.071.1-0_amd64.deb; sudo dpkg -i dmd_2.071.1-0_amd64.deb
  - sudo apt-get install -y gnu-smalltalk
  - sudo apt-get install -y php5
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb; sudo dpkg -i erlang-solutions_1.0_all.deb; sudo apt-get update
  - sudo apt-get install emacs25; sudo apt-get install -y erlang
  - sudo apt-get install -y elixir
  - sudo apt-get install -y r-base
  - curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash; sudo apt-get install -y crystal
  - wget http://nim-lang.org/download/nim-0.14.2.tar.xz && tar xvf nim-0.14.2.tar.xz && cd nim-0.14.2 && sh build.sh && cd ../ && export PATH=$PWD/nim-0.14.2/bin:$PATH
  - npm install -g bower
  - npm install -g coffee-script
  - npm install -g livescript
  - npm install -g typescript ts-node
  - npm install -g purescript pulp
  - sudo apt-get install -y libedit-dev; wget http://www.jsoftware.com/download/j805/install/j805_linux64.tar.gz; tar xzvf j805_linux64.tar.gz; export PATH=$PWD/j64-805/bin:$PATH
  - sudo apt-get install -y gauche
  - sudo apt-get install -y ocaml
  - wget http://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.zip && unzip clojure-1.8.0.zip && mv clojure-1.8.0/clojure-1.8.0.jar src/clojure/

script:
  - make build
  - bash script/test.sh
