language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs
  - sudo apt-get install -y scala

script:
  - make build
  - bash script/test.sh
