language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y gnustep-devel
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs
  - wget http://www.scala-lang.org/files/archive/scala-2.11.8.deb; sudo dpkg -i scala-2.11.8.deb
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.0.3/kotlin-compiler-1.0.3.zip; unzip kotlin-compiler-1.0.3.zip; export PATH=$PWD/kotlinc/bin:$PATH
  - wget http://downloads.dlang.org/releases/2016/dmd_2.071.1-0_amd64.deb; sudo dpkg -i dmd_2.071.1-0_amd64.deb
  - wget http://www.jsoftware.com/download/j805/install/j805_linux64.tar.gz; tar xzvf j805_linux64.tar.gz; export PATH=$PWD/j64-805/bin:$PATH

script:
  - make build
  - bash script/test.sh
