language: c

sudo: required

dist: trusty

install:
  - sudo apt-get install -y gnustep-devel
  - sudo apt-get install -y ghc
  - sudo apt-get install -y mono-devel mono-gmcs mono-complete mono-vbnc fsharp
  - wget http://www.scala-lang.org/files/archive/scala-2.11.8.deb; sudo dpkg -i scala-2.11.8.deb
  - curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh
  - wget https://github.com/JetBrains/kotlin/releases/download/v1.0.3/kotlin-compiler-1.0.3.zip; unzip kotlin-compiler-1.0.3.zip; export PATH=$PWD/kotlinc/bin:$PATH
  - sudo apt-get install -y groovy
  - wget http://downloads.dlang.org/releases/2016/dmd_2.071.1-0_amd64.deb; sudo dpkg -i dmd_2.071.1-0_amd64.deb
  - sudo apt-get install -y php5
  - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb; sudo dpkg -i erlang-solutions_1.0_all.deb; sudo apt-get update
  - sudo apt-get install -y erlang
  - sudo apt-get install -y elixir
  - curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash; sudo apt-get install -y crystal
  - npm install -g coffee-script
  - npm install -g typescript ts-node
  - sudo apt-get install -y libedit-dev; wget http://www.jsoftware.com/download/j805/install/j805_linux64.tar.gz; tar xzvf j805_linux64.tar.gz; export PATH=$PWD/j64-805/bin:$PATH
  - sudo apt-get install -y gauche
  - sudo apt-get install -y ocaml
  - wget http://repo1.maven.org/maven2/org/clojure/clojure/1.8.0/clojure-1.8.0.zip && unzip clojure-1.8.0.zip && mv clojure-1.8.0/clojure-1.8.0.jar src/clojure/

script:
  - make build
  - bash script/test.sh
